'use client'
// import type { Metadata } from 'next'
import { AiFillHome } from 'react-icons/ai';
import { BsCashStack } from 'react-icons/bs';
import { FaMoneyCheckAlt } from 'react-icons/fa';
import { BiSolidVideos, BiSolidContact } from 'react-icons/bi';

import TabNavigation from '@/components/TabNavigation';


// export const metadata: Metadata = {
//    title: 'Create Next App',
//    description: 'Generated by create next app',
// }

export default function RootLayout({
   children,
}: {
   children: React.ReactNode
}) {
   return (
      <>
         <div className='h-screen w-full overflow-auto'>
            <div className='h-full w-full'>
               {children}
            </div>
            <TabNavigation
               items={[
                  { icon: AiFillHome, label: 'Inicio', to: '/home' },
                  { icon: BiSolidVideos, label: 'Videos', to: '/videos' },
                  { icon: BiSolidContact, label: 'Referidos', to: '/referrals' },
                  { icon: FaMoneyCheckAlt, label: 'Depósitos', to: '/deposits' },
                  { icon: BsCashStack, label: 'Retiros', to: '/cashout' },
               ]}
            />
         </div>
      </>
   )
}
